// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Compress(arg1) {
  return window['go']['main']['App']['Compress'](arg1);
}

export function Convert(arg1) {
  return window['go']['main']['App']['Convert'](arg1);
}

export function SelectInputFile() {
  return window['go']['main']['App']['SelectInputFile']();
}
