// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Compress(arg1:main.CompressRequest):Promise<main.ConvertResult>;

export function Convert(arg1:main.ConvertRequest):Promise<main.ConvertResult>;

export function SelectInputFile():Promise<string>;
